// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module VGA(	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
  input         clock,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
                reset,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
  input  [31:0] io_mmio_address,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
                io_mmio_write_data,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
  input         io_mmio_write_enable,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
  output [31:0] io_mmio_read_data,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
  input         io_pixClock,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
  output        io_hsync,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
                io_vsync,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
  output [5:0]  io_rrggbb,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
  output        io_activevideo,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
                io_intr,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
  output [9:0]  io_x_pos,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
                io_y_pos	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
);

  wire [31:0]      _framebuffer_doutb;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:101:27
  reg  [31:0]      ctrlReg;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:107:30
  reg  [31:0]      intrStatusReg;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:108:30
  reg  [31:0]      uploadAddrReg;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:109:30
  reg  [5:0]       paletteReg_0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_2;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_3;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_4;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_5;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_6;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_7;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_8;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_9;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_10;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_11;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_12;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_13;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_14;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  reg  [5:0]       paletteReg_15;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23
  wire             addr_ctrl = io_mmio_address[7:0] == 8'h4;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:132:44, :133:33
  wire             addr_intr_status = io_mmio_address[7:0] == 8'hC;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:132:44, :134:33
  wire             addr_upload_addr = io_mmio_address[7:0] == 8'h10;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:132:44, :135:33
  wire             addr_stream_data = io_mmio_address[7:0] == 8'h14;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:132:44, :136:33
  reg              vblank_sync1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:141:36
  reg              vblank_synced;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:142:36
  reg  [3:0]       curr_frame_sync1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:143:36
  reg  [3:0]       curr_frame_synced;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:144:36
  reg              vblank_prev;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:153:37
  wire             _GEN = addr_ctrl | addr_intr_status | addr_upload_addr;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:133:33, :134:33, :135:33, :184:36, :190:23, :201:36, :204:36, :206:36
  wire             _GEN_0 = ~io_mmio_write_enable | _GEN | ~addr_stream_data;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:136:33, :156:48, :184:36, :185:36, :189:32, :190:23, :201:36, :204:36, :206:36
  reg  [9:0]       h_count;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:237:26
  reg  [9:0]       v_count;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:238:26
  reg              hsync_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:257:31
  reg              vsync_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:258:31
  reg              io_hsync_REG;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:259:24
  reg              io_vsync_REG;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:260:24
  reg  [9:0]       x_px;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:269:23
  reg  [9:0]       y_px;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:270:23
  wire             _rel_y_T = y_px > 10'h2F;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:270:23, :274:30
  wire [23:0]      frame_x_mult =
    {14'h0, (|(x_px[9:7])) ? x_px - 10'h80 : 10'h0} * 24'h2AAB;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:269:23, :273:30, :279:{20,49}, :287:30
  wire [23:0]      frame_y_mult = {14'h0, _rel_y_T ? y_px - 10'h30 : 10'h0} * 24'h2AAB;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:270:23, :274:30, :280:{20,48}, :287:30, :289:30
  reg  [3:0]       curr_frame_sync1_1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:298:35
  reg  [3:0]       curr_frame;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:299:35
  reg              display_enabled_sync1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:301:40
  reg              display_enabled;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:302:40
  reg              blanking_sync1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:304:33
  reg              blanking;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:305:33
  reg  [5:0]       palette_sync1_0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_2;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_3;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_4;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_5;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_6;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_7;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_8;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_9;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_10;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_11;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_12;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_13;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_14;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync1_15;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32
  reg  [5:0]       palette_sync_0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_2;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_3;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_4;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_5;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_6;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_7;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_8;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_9;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_10;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_11;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_12;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_13;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_14;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg  [5:0]       palette_sync_15;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31
  reg              in_display_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:316:37
  reg              h_active_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:319:30
  reg              v_active_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:320:30
  reg              h_active_d2;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:321:30
  reg              v_active_d2;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:322:30
  wire [12:0]      _pixel_idx_T_1 =
    {1'h0, (|(frame_y_mult[23:22])) ? 6'h3F : frame_y_mult[21:16], 6'h0}
    + {7'h0, (|(frame_x_mult[23:22])) ? 6'h3F : frame_x_mult[21:16]};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:287:30, :288:36, :289:30, :290:36, :293:{22,35,85}, :294:{22,35,87}, :326:49
  reg  [2:0]       pixel_in_word_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:338:35
  wire [7:0][3:0]  _GEN_1 =
    {{_framebuffer_doutb[31:28]},
     {_framebuffer_doutb[27:24]},
     {_framebuffer_doutb[23:20]},
     {_framebuffer_doutb[19:16]},
     {_framebuffer_doutb[15:12]},
     {_framebuffer_doutb[11:8]},
     {_framebuffer_doutb[7:4]},
     {_framebuffer_doutb[3:0]}};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:101:27, :343:51, :345:23, :346:23, :347:23, :348:23, :349:23, :350:23, :351:23, :352:23
  wire [15:0][5:0] _GEN_2 =
    {{palette_sync_15},
     {palette_sync_14},
     {palette_sync_13},
     {palette_sync_12},
     {palette_sync_11},
     {palette_sync_10},
     {palette_sync_9},
     {palette_sync_8},
     {palette_sync_7},
     {palette_sync_6},
     {palette_sync_5},
     {palette_sync_4},
     {palette_sync_3},
     {palette_sync_2},
     {palette_sync_1},
     {palette_sync_0}};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:311:31, :363:20
  wire             io_activevideo_0 = h_active_d2 & v_active_d2;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:321:30, :322:30, :369:34
  reg  [9:0]       x_px_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:376:26
  reg  [9:0]       y_px_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:377:26
  always @(posedge clock) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
    automatic logic       addr_palette =
      (|(io_mmio_address[7:5])) & {24'h0, io_mmio_address[7:0]} < 32'h60;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:132:44, :137:{34,45,54}
    automatic logic [5:0] _GEN_3 = io_mmio_address[5:0] - 6'h20;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:132:44, :138:35
    automatic logic       _GEN_4 =
      addr_ctrl | addr_intr_status | addr_upload_addr | addr_stream_data;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :133:33, :134:33, :135:33, :136:33, :190:23, :201:36, :204:36, :206:36, :223:32
    if (reset) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
      ctrlReg <= 32'h0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:107:30
      intrStatusReg <= 32'h0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:108:30
      uploadAddrReg <= 32'h0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:109:30
    end
    else begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
      if (io_mmio_write_enable & addr_ctrl)	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:107:30, :133:33, :189:32, :190:23, :195:38
        ctrlReg <=
          io_mmio_write_data[7:6] != 2'h3
            ? io_mmio_write_data
            : {ctrlReg[31:4], 3'h0, io_mmio_write_data[0]};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:107:30, :118:31, :194:49, :195:{30,38}, :196:19, :199:{19,25,33}
      if (~io_mmio_write_enable | addr_ctrl | ~addr_intr_status) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:133:33, :134:33, :156:48, :189:32, :190:23, :201:36
        if (vblank_synced & ~vblank_prev & ctrlReg[8])	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:107:30, :119:31, :142:36, :153:37, :154:{44,47}, :156:29
          intrStatusReg <= 32'h1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:108:30
      end
      else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:156:48, :189:32, :190:23, :201:36
        intrStatusReg <= intrStatusReg & ~io_mmio_write_data;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:108:30, :203:{40,42}
      if (~io_mmio_write_enable | addr_ctrl | addr_intr_status) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:109:30, :133:33, :134:33, :156:48, :189:32, :190:23, :201:36, :204:36
      end
      else if (addr_upload_addr)	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:135:33
        uploadAddrReg <= io_mmio_write_data;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:109:30
      else if (addr_stream_data) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:136:33
        automatic logic [15:0] _next_addr_T;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:220:44
        _next_addr_T = uploadAddrReg[15:0] + 16'h8;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:109:30, :128:40, :220:44
        uploadAddrReg <=
          {12'h0, uploadAddrReg[19:16], (|(_next_addr_T[15:12])) ? 16'h0 : _next_addr_T};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:109:30, :129:40, :220:44, :221:{31,42}, :222:23
      end
    end
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'h0)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_0 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'h1)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_1 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'h2)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_2 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'h3)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_3 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'h4)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_4 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'h5)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_5 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'h6)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_6 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'h7)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_7 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'h8)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_8 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'h9)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_9 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'hA)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_10 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'hB)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_11 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'hC)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_12 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'hD)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_13 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & _GEN_3[5:2] == 4'hE)) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_14 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    if (~io_mmio_write_enable | _GEN_4 | ~(addr_palette & (&(_GEN_3[5:2])))) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :132:44, :137:45, :138:{35,45,50}, :156:48, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32, :224:33
    end
    else	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :189:32, :190:23, :201:36, :204:36, :206:36, :223:32
      paletteReg_15 <= io_mmio_write_data[5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :224:54
    vblank_sync1 <= v_count > 10'h1DF;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:141:36, :238:26, :382:29
    vblank_synced <= vblank_sync1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:141:36, :142:36
    curr_frame_sync1 <= curr_frame;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:143:36, :299:35
    curr_frame_synced <= curr_frame_sync1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:143:36, :144:36
    vblank_prev <= vblank_synced;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:142:36, :153:37
  end // always @(posedge)
  always @(posedge io_pixClock) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
    if (reset) begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
      h_count <= 10'h0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:237:26
      v_count <= 10'h0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:238:26
    end
    else begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:56:14
      automatic logic _GEN_5;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:241:18
      _GEN_5 = h_count == 10'h33F;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:237:26, :241:18
      h_count <= _GEN_5 ? 10'h0 : h_count + 10'h1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:237:26, :241:{18,39}, :242:15, :250:{15,26}
      if (_GEN_5)	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:241:18
        v_count <= v_count == 10'h207 ? 10'h0 : v_count + 10'h1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:238:26, :244:{20,41}, :245:17, :247:{17,28}
    end
    hsync_d1 <= ~(h_count > 10'h297 & h_count < 10'h2C0);	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:237:26, :255:{33,57,69}, :257:{31,32}
    vsync_d1 <= ~(v_count > 10'h1E8 & v_count < 10'h1EC);	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:238:26, :256:{33,57,69}, :258:{31,32}
    io_hsync_REG <= hsync_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:257:31, :259:24
    io_vsync_REG <= vsync_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:258:31, :260:24
    x_px <= h_count;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:237:26, :269:23
    y_px <= v_count;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:238:26, :270:23
    curr_frame_sync1_1 <= ctrlReg[7:4];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:107:30, :118:31, :298:35
    curr_frame <= curr_frame_sync1_1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:298:35, :299:35
    display_enabled_sync1 <= ctrlReg[0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:107:30, :115:31, :301:40
    display_enabled <= display_enabled_sync1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:301:40, :302:40
    blanking_sync1 <= ctrlReg[1];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:107:30, :116:31, :304:33
    blanking <= blanking_sync1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:304:33, :305:33
    palette_sync1_0 <= paletteReg_0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_1 <= paletteReg_1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_2 <= paletteReg_2;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_3 <= paletteReg_3;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_4 <= paletteReg_4;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_5 <= paletteReg_5;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_6 <= paletteReg_6;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_7 <= paletteReg_7;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_8 <= paletteReg_8;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_9 <= paletteReg_9;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_10 <= paletteReg_10;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_11 <= paletteReg_11;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_12 <= paletteReg_12;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_13 <= paletteReg_13;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_14 <= paletteReg_14;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync1_15 <= paletteReg_15;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:112:23, :309:32
    palette_sync_0 <= palette_sync1_0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_1 <= palette_sync1_1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_2 <= palette_sync1_2;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_3 <= palette_sync1_3;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_4 <= palette_sync1_4;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_5 <= palette_sync1_5;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_6 <= palette_sync1_6;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_7 <= palette_sync1_7;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_8 <= palette_sync1_8;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_9 <= palette_sync1_9;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_10 <= palette_sync1_10;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_11 <= palette_sync1_11;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_12 <= palette_sync1_12;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_13 <= palette_sync1_13;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_14 <= palette_sync1_14;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    palette_sync_15 <= palette_sync1_15;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:309:32, :311:31
    in_display_d1 <= (|(x_px[9:7])) & ~(x_px[9]) & _rel_y_T & y_px < 10'h1B0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:269:23, :270:23, :273:{30,48,57}, :274:{30,47,56}, :275:37, :316:37
    h_active_d1 <= h_count < 10'h280;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:237:26, :263:28, :319:30
    v_active_d1 <= v_count < 10'h1E0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:238:26, :264:28, :320:30
    h_active_d2 <= h_active_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:319:30, :321:30
    v_active_d2 <= v_active_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:320:30, :322:30
    pixel_in_word_d1 <= _pixel_idx_T_1[2:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:326:49, :328:34, :338:35
    x_px_d1 <= x_px;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:269:23, :376:26
    y_px_d1 <= y_px;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:270:23, :377:26
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
      `FIRRTL_BEFORE_INITIAL	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
      automatic logic [31:0] _RANDOM[0:14];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
      `ifdef INIT_RANDOM_PROLOG_	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
        `INIT_RANDOM_PROLOG_	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
        for (logic [3:0] i = 4'h0; i < 4'hF; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
        end	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
        ctrlReg = _RANDOM[4'h0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :107:30
        intrStatusReg = _RANDOM[4'h1];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :108:30
        uploadAddrReg = _RANDOM[4'h2];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :109:30
        paletteReg_0 = _RANDOM[4'h3][5:0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_1 = _RANDOM[4'h3][11:6];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_2 = _RANDOM[4'h3][17:12];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_3 = _RANDOM[4'h3][23:18];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_4 = _RANDOM[4'h3][29:24];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_5 = {_RANDOM[4'h3][31:30], _RANDOM[4'h4][3:0]};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_6 = _RANDOM[4'h4][9:4];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_7 = _RANDOM[4'h4][15:10];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_8 = _RANDOM[4'h4][21:16];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_9 = _RANDOM[4'h4][27:22];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_10 = {_RANDOM[4'h4][31:28], _RANDOM[4'h5][1:0]};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_11 = _RANDOM[4'h5][7:2];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_12 = _RANDOM[4'h5][13:8];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_13 = _RANDOM[4'h5][19:14];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_14 = _RANDOM[4'h5][25:20];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        paletteReg_15 = _RANDOM[4'h5][31:26];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :112:23
        vblank_sync1 = _RANDOM[4'h6][0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :141:36
        vblank_synced = _RANDOM[4'h6][1];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :141:36, :142:36
        curr_frame_sync1 = _RANDOM[4'h6][5:2];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :141:36, :143:36
        curr_frame_synced = _RANDOM[4'h6][9:6];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :141:36, :144:36
        vblank_prev = _RANDOM[4'h6][10];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :141:36, :153:37
        h_count = _RANDOM[4'h6][20:11];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :141:36, :237:26
        v_count = _RANDOM[4'h6][30:21];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :141:36, :238:26
        hsync_d1 = _RANDOM[4'h6][31];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :141:36, :257:31
        vsync_d1 = _RANDOM[4'h7][0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :258:31
        io_hsync_REG = _RANDOM[4'h7][1];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :258:31, :259:24
        io_vsync_REG = _RANDOM[4'h7][2];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :258:31, :260:24
        x_px = _RANDOM[4'h7][12:3];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :258:31, :269:23
        y_px = _RANDOM[4'h7][22:13];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :258:31, :270:23
        curr_frame_sync1_1 = _RANDOM[4'h7][26:23];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :258:31, :298:35
        curr_frame = _RANDOM[4'h7][30:27];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :258:31, :299:35
        display_enabled_sync1 = _RANDOM[4'h7][31];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :258:31, :301:40
        display_enabled = _RANDOM[4'h8][0];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :302:40
        blanking_sync1 = _RANDOM[4'h8][1];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :302:40, :304:33
        blanking = _RANDOM[4'h8][2];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :302:40, :305:33
        palette_sync1_0 = _RANDOM[4'h8][8:3];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :302:40, :309:32
        palette_sync1_1 = _RANDOM[4'h8][14:9];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :302:40, :309:32
        palette_sync1_2 = _RANDOM[4'h8][20:15];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :302:40, :309:32
        palette_sync1_3 = _RANDOM[4'h8][26:21];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :302:40, :309:32
        palette_sync1_4 = {_RANDOM[4'h8][31:27], _RANDOM[4'h9][0]};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :302:40, :309:32
        palette_sync1_5 = _RANDOM[4'h9][6:1];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync1_6 = _RANDOM[4'h9][12:7];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync1_7 = _RANDOM[4'h9][18:13];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync1_8 = _RANDOM[4'h9][24:19];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync1_9 = _RANDOM[4'h9][30:25];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync1_10 = {_RANDOM[4'h9][31], _RANDOM[4'hA][4:0]};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync1_11 = _RANDOM[4'hA][10:5];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync1_12 = _RANDOM[4'hA][16:11];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync1_13 = _RANDOM[4'hA][22:17];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync1_14 = _RANDOM[4'hA][28:23];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync1_15 = {_RANDOM[4'hA][31:29], _RANDOM[4'hB][2:0]};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32
        palette_sync_0 = _RANDOM[4'hB][8:3];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32, :311:31
        palette_sync_1 = _RANDOM[4'hB][14:9];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32, :311:31
        palette_sync_2 = _RANDOM[4'hB][20:15];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32, :311:31
        palette_sync_3 = _RANDOM[4'hB][26:21];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32, :311:31
        palette_sync_4 = {_RANDOM[4'hB][31:27], _RANDOM[4'hC][0]};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :309:32, :311:31
        palette_sync_5 = _RANDOM[4'hC][6:1];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        palette_sync_6 = _RANDOM[4'hC][12:7];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        palette_sync_7 = _RANDOM[4'hC][18:13];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        palette_sync_8 = _RANDOM[4'hC][24:19];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        palette_sync_9 = _RANDOM[4'hC][30:25];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        palette_sync_10 = {_RANDOM[4'hC][31], _RANDOM[4'hD][4:0]};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        palette_sync_11 = _RANDOM[4'hD][10:5];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        palette_sync_12 = _RANDOM[4'hD][16:11];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        palette_sync_13 = _RANDOM[4'hD][22:17];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        palette_sync_14 = _RANDOM[4'hD][28:23];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        palette_sync_15 = {_RANDOM[4'hD][31:29], _RANDOM[4'hE][2:0]};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31
        in_display_d1 = _RANDOM[4'hE][3];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31, :316:37
        h_active_d1 = _RANDOM[4'hE][4];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31, :319:30
        v_active_d1 = _RANDOM[4'hE][5];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31, :320:30
        h_active_d2 = _RANDOM[4'hE][6];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31, :321:30
        v_active_d2 = _RANDOM[4'hE][7];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31, :322:30
        pixel_in_word_d1 = _RANDOM[4'hE][10:8];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31, :338:35
        x_px_d1 = _RANDOM[4'hE][20:11];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31, :376:26
        y_px_d1 = _RANDOM[4'hE][30:21];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :311:31, :377:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
      `FIRRTL_AFTER_INITIAL	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TrueDualPortRAM32 #(
    .ADDR_WIDTH(13),
    .DEPTH(6144)
  ) framebuffer (	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:101:27
    .clka  (clock),
    .wea   (io_mmio_write_enable & ~_GEN & addr_stream_data),	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:136:33, :184:36, :189:32, :190:23, :201:36, :204:36, :206:36
    .addra (_GEN_0 ? 13'h0 : {uploadAddrReg[19:16], 9'h0} + uploadAddrReg[15:3]),	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:109:30, :128:40, :129:40, :185:36, :189:32, :190:23, :201:36, :204:36, :206:36, :210:51, :212:44
    .dina  (_GEN_0 ? 32'h0 : io_mmio_write_data),	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:185:36, :186:36, :189:32, :190:23, :201:36, :204:36, :206:36
    .clkb  (io_pixClock),
    .addrb ({curr_frame, 9'h0} + {3'h0, _pixel_idx_T_1[12:3]}),	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:299:35, :326:49, :327:35, :330:36
    .doutb (_framebuffer_doutb)
  );	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:101:27
  assign io_mmio_read_data =
    io_mmio_address[7:0] == 8'h5C
      ? {26'h0, paletteReg_15}
      : io_mmio_address[7:0] == 8'h58
          ? {26'h0, paletteReg_14}
          : io_mmio_address[7:0] == 8'h54
              ? {26'h0, paletteReg_13}
              : io_mmio_address[7:0] == 8'h50
                  ? {26'h0, paletteReg_12}
                  : io_mmio_address[7:0] == 8'h4C
                      ? {26'h0, paletteReg_11}
                      : io_mmio_address[7:0] == 8'h48
                          ? {26'h0, paletteReg_10}
                          : io_mmio_address[7:0] == 8'h44
                              ? {26'h0, paletteReg_9}
                              : io_mmio_address[7:0] == 8'h40
                                  ? {26'h0, paletteReg_8}
                                  : io_mmio_address[7:0] == 8'h3C
                                      ? {26'h0, paletteReg_7}
                                      : io_mmio_address[7:0] == 8'h38
                                          ? {26'h0, paletteReg_6}
                                          : io_mmio_address[7:0] == 8'h34
                                              ? {26'h0, paletteReg_5}
                                              : io_mmio_address[7:0] == 8'h30
                                                  ? {26'h0, paletteReg_4}
                                                  : io_mmio_address[7:0] == 8'h2C
                                                      ? {26'h0, paletteReg_3}
                                                      : io_mmio_address[7:0] == 8'h28
                                                          ? {26'h0, paletteReg_2}
                                                          : io_mmio_address[7:0] == 8'h24
                                                              ? {26'h0, paletteReg_1}
                                                              : io_mmio_address[7:0] == 8'h20
                                                                  ? {26'h0, paletteReg_0}
                                                                  : addr_upload_addr
                                                                      ? uploadAddrReg
                                                                      : addr_intr_status
                                                                          ? intrStatusReg
                                                                          : io_mmio_address[7:0] == 8'h8
                                                                              ? {23'h0,
                                                                                 curr_frame_synced,
                                                                                 3'h0,
                                                                                 {2{vblank_synced}}}
                                                                              : addr_ctrl
                                                                                  ? ctrlReg
                                                                                  : {1'h0,
                                                                                     io_mmio_address[7:0] == 8'h0
                                                                                       ? 31'h56474131
                                                                                       : 31'h0};	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :107:30, :108:30, :109:30, :112:23, :132:44, :133:33, :134:33, :135:33, :142:36, :144:36, :163:46, :167:22
  assign io_hsync = io_hsync_REG;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :259:24
  assign io_vsync = io_vsync_REG;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :260:24
  assign io_rrggbb =
    ~io_activevideo_0 | blanking
      ? 6'h0
      : display_enabled & in_display_d1 ? _GEN_2[_GEN_1[pixel_in_word_d1]] : 6'h1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :302:40, :305:33, :316:37, :338:35, :343:51, :362:{32,50}, :363:20, :365:20, :369:{21,34}
  assign io_activevideo = io_activevideo_0;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :369:34
  assign io_intr = (|intrStatusReg) & ctrlReg[8];	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :107:30, :108:30, :119:31, :160:{31,40}
  assign io_x_pos = x_px_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :376:26
  assign io_y_pos = y_px_d1;	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VGA.scala:55:7, :377:26
endmodule

