// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
module VgaStandaloneWrapper(	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:24:7
  input         clock,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:24:7
                reset,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:24:7
  input  [31:0] io_mmio_addr,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
                io_mmio_wdata,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
  input         io_mmio_wen,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
  output [31:0] io_mmio_rdata,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
  input         io_pixClock,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
  output        io_hsync,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
                io_vsync,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
  output [5:0]  io_rgb,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
  output        io_activevideo,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
  output [9:0]  io_x_pos,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
                io_y_pos,	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
  output        io_intr	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:25:14
);

  VGA vga (	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:43:19
    .clock                (clock),
    .reset                (reset),
    .io_mmio_address      (io_mmio_addr),
    .io_mmio_write_data   (io_mmio_wdata),
    .io_mmio_write_enable (io_mmio_wen),
    .io_mmio_read_data    (io_mmio_rdata),
    .io_pixClock          (io_pixClock),
    .io_hsync             (io_hsync),
    .io_vsync             (io_vsync),
    .io_rrggbb            (io_rgb),
    .io_activevideo       (io_activevideo),
    .io_intr              (io_intr),
    .io_x_pos             (io_x_pos),
    .io_y_pos             (io_y_pos)
  );	// home/tobyphant/Documents/coding/Rework-Coral-NPU-as-standalone-RV32IMF_Zve32x-RISC-V-core/hdl/chisel/src/peripherals/VgaStandaloneWrapper.scala:43:19
endmodule

